### ISSUE TITLE
Update addin to latest guidelines

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Transifex#26]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [ ] You are currently referencing Cake.Core 0.26.0. Please upgrade to 0.28.0
- [ ] The Cake.Core reference should be private. Specifically, your addin's `.csproj` should have a line similar to this: `<PackageReference Include="Cake.Core" Version="0.28.0" PrivateAssets="All" />`
- [ ] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by AdmiringWorm** [comment]
Just a few things I would like to respond to

> You are currently referencing Cake.Core 0.26.0. Please upgrade to 0.28.0

AFAIK, there hasn't been any breaking changes since 0.26.0 to the current version, as such I don't really see any reason to update the dependency (better to have a lower version, to allow users to use a previous version of Cake if they wish).

> Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.

Actually, there may be a need depending on how the users development environment is set up.
If changing to only use netstandard2.0, it would require the user to either
1. Install Visual Studio 2017
2. Install an additional extension for Visual Studio 2015 to support adding netstandard2.0 libraries when running through .NET Framework.

Additional configuration may be required on the users development environment (Can't verify that though).

**Comment by Jericho** [comment]
If you don't upgrade to 0.28.0, people who run a script that reference your addin will see a warning similar to this one:

```
The assembly 'Cake.Coveralls, Version=0.8.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.0).
For best compatibility it should target Cake.Core version 0.28.0.
```

**Comment by AdmiringWorm** [comment]
I see, I guess I should update the dependency then at least.
Still hesitant to change the multi-targeting though.

**Comment by Jericho** [comment]
Regarding the framework target: I understand your point about additional set up required but the rational for the target recommendation is not based on the addin author's machine but rather based on Cake's requirements.

We might want to involve @mholo65 for authoritative answer on this but my understanding is that Cake dictates the framework when your addin is loaded so you should match the framework.

But before I put my foot in my mouth and say something that is not completely accurate, I'll let @mholo65  chime in.

**Comment by AdmiringWorm** [comment]
I've decided to remove the multi-targeting, however would still love some clarification on this though.

**Comment by Jericho** [comment]
I was just chatting with @gep13 about this and we agreed the the [guidelines document](https://github.com/cake-contrib/Home/blob/master/Guidelines.md) should be updated and it should contain a clear explanation why netstandard2.0 is the recommended target.

I have agreed to work on the PR to update the document but I will need help from the core cake team to come up with the clear explanation.

**Comment by AdmiringWorm** [comment]
Awesome, I'll look forward to the update

**Comment by mholo65** [comment]
Regarding multitargeting. It’s perfectly fine to target both `net46` (or even `net461`) and `netstandard2.0` for any addin. If your addin only targets one framework, then `netstandard2.0` is prefered as it is compatible with both `cake` and `cake.coreclr`.

Previously, before moving to dotnet core 2, the only way to support both `cake` and `cake.coreclr` was to multitarget (`net46` and `netstandard1.6`). Nowadays there’s (in most cases) no real need to multitarget, but many addins still due (mainly because they did it earlier).

**Comment by Jericho** [comment]
FYI: created a [ticket](https://github.com/cake-contrib/Home/issues/49) to track discussion regarding updating guidelines document
